# Generated by Django 4.0.3 on 2022-05-23 23:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_remove_pessoa_estados_cidade_estados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(help_text='Digite seu nome completo', max_length=50, verbose_name='Qual seu nome?')),
                ('nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('email', models.EmailField(max_length=100)),
                ('contato', models.IntegerField(help_text='Exemplo: 44997253416', validators=[django.core.validators.MaxValueValidator(15)], verbose_name='Numero de celular:')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paginas.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('inicio', models.DateField(verbose_name='Data da reserva do veiculo')),
                ('fim', models.DateField(verbose_name='Data da entrega do veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Exemplo: Mazda RX7', max_length=50, verbose_name='Qual é o veiculo ?')),
                ('data', models.DateField(help_text='Exemplo: 06/02/2014', verbose_name='Data do veiculo')),
                ('cor', models.CharField(help_text='Exemplo: Vermelho, Prata, Preto...', max_length=20, verbose_name='Qual a cor do veiculo ?')),
                ('diaria', models.IntegerField(help_text='Exemplo: 150, 200, 500 ...', verbose_name='Qual o valor da diaria do veiculo ?')),
                ('qtn_bancos', models.IntegerField(help_text='Exemplo: 3, 4, 5 ...', validators=[django.core.validators.MaxValueValidator(8)], verbose_name='Qual a quantidade de bancos do veiculo ?')),
                ('gasto_gasolina_km', models.IntegerField(help_text='Exemplo: 3, 4, 5 ...', validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Quanto que o veiculo gasta de gasolina por KM ?')),
                ('modelo_motor', models.CharField(max_length=20, verbose_name='Qual o modelo do motor ?')),
                ('velocidade_max', models.CharField(max_length=50, verbose_name='Qual a velocidade maxima do veiculo ?')),
            ],
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
