# Generated by Django 4.0.3 on 2022-05-30 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_funcionario_reserva_veiculo_delete_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='gasto_gasolina_km',
            field=models.IntegerField(help_text='Exemplo: 3, 4, 5 ...', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Quanto que o veiculo gasta de gasolina por KM ?'),
        ),
    ]
